name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify_files:
    permissions:
      contents: write
    name: Deploy sample docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{github.token}}
          destination_dir: ./${{github.sha}}
          publish_dir: dist
          enable_jekyll: false
          keep_files: true
